LWDEV-9144 LWDEV-8406
LykkeCity/Lykke.Service.Decred.Sign pull request #1
Opened 2018-08-31 14:11 UTC by some-dev

2018-09-02 14:01 UTC, PaterSantyago submitted a review, later dismissed

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Domain/Health/HealthIssue.cs
> +    public class HealthIssue
Let's use health-related staff from common libraries

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Domain/Health/HealthIssuesCollection.cs
> +    public class HealthIssuesCollection : IReadOnlyCollection<HealthIssue>
Let's use health-related staff from common libraries

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Services/IHealthService.cs
> +    public interface IHealthService
Let's use health-related staff from common libraries

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Services/IShutdownManager.cs
> +    public interface IShutdownManager
Let's use SDK approach, instead of IShutdownManager

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Services/IStartupManager.cs
> +    public interface IStartupManager
Let's use SDK approach instead of IStartupManager

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Services/ShutdownManager.cs
> +    public class ShutdownManager : IShutdownManager
Let's use SDK

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Services/SigningService.cs
> +    public interface ISigningService
One class/interface - one file is a good rule. Seriously. We have no problems with large number of files.

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Services/StartupManager.cs
> +    public class StartupManager : IStartupManager
And again, let's use SDK

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Controllers/IsAliveController.cs
> +    public class IsAliveController : Controller
SDK and modern template...

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Controllers/SignController.cs
> +        [ProducesResponseType(typeof(ErrorResponse), (int)HttpStatusCode.BadRequest)]
We are using hand-tailored client for all blockchain implementations, so swagger-oriented attributes are not necessary

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/ErrorResponse.cs
> +    public class ErrorResponse
Let's use ErrorResponse from common library

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/IsAliveResponse.cs
> +    public class IsAliveResponse
This model is not necessary, we can use IsAliveController from common libraries

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/SignTransactionRequest.cs
> +    public class SignTransactionRequest : IValidatableObject
We strictly should use model from contract

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/SignedTransactionResponse.cs
> +    public class SignedTransactionResponse
We strictly should use model from contract

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Program.cs
> +    public class Program
Let's refactor it according to the modern template and Lykke.SDK

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Startup.cs
> +    public class Startup
Let's refactor it according to the modern template and Lykke.SDK

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Startup.cs
> +                    networkType == "test" ? "testnet" :
It's not good-readable code

2018-09-02 14:01 UTC, PaterSantyago commented on tests/Lykke.Service.Decred.SignService.Services.Tests/SigningServiceTests.cs
> +        private string[] _keys =
Let's use Theorem and InlineData

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Program.cs
> +                        logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
Logging should either be removed, or disabled with build configuration for test and prod environments

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Domain/Readme.md
> +﻿Place domain entities, which are used in services layer, their interfaces and repository's interfaces here
Let's remove this readme

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Services/Readme.md
> +﻿Place implementations of your services in this folder. Group their in subfolder by business functions
Let's rem move this readme

2018-09-02 14:01 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Startup.cs
> +            services.AddTransient<ISigningWallet, SigningWallet>();
Let's use autofac

2018-09-02 19:39 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService/Startup.cs
> +            services.AddTransient<ISigningWallet, SigningWallet>();
Why, what's wrong with the existing code?

2018-09-02 19:41 UTC, sefbkn commented on tests/Lykke.Service.Decred.SignService.Services.Tests/SigningServiceTests.cs
> +        private string[] _keys =
What's wrong with the current style?

2018-09-02 19:42 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService.Core/Services/IHealthService.cs
> +    public interface IHealthService
Do you have a concrete example of how this should be done?

2018-09-02 19:42 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService.Core/Services/IShutdownManager.cs
> +    public interface IShutdownManager
Do you have a concrete example of how this should be done?

2018-09-02 19:44 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService/Program.cs
> +                        logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
What's the expectation on how this should look?  I do not see this requirement documented currently.

2018-09-06 07:37 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Startup.cs
> +            services.AddTransient<ISigningWallet, SigningWallet>();
Autofac is a standard de-facto among Lykke's project, also it's used by Lykke's modern service template

2018-09-06 07:38 UTC, PaterSantyago commented on tests/Lykke.Service.Decred.SignService.Services.Tests/SigningServiceTests.cs
> +        private string[] _keys =
It's ok, but Theorem + InlineData is a framework feature, made especially for such cases

2018-09-06 07:47 UTC, PaterSantyago commented
@sefbkn You can find examples of modern template and SDK usage here:
https://github.com/LykkeCity/Lykke.Service.Bitcoin.Api/tree/dev/src/Lykke.Service.Bitcoin.Api and https://github.com/LykkeCity/Lykke.Service.BitcoinGold.Sign/tree/dev/src/Lykke.Service.BitcoinGold.Sign

Also, sign service implementation covers disabling of logging.

2018-09-08 18:28 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService/Models/SignTransactionRequest.cs
> +    public class SignTransactionRequest : IValidatableObject
Where is this defined in the contract?

https://github.com/LykkeCity/Lykke.Service.Bitcoin.Sign/blob/dev/src/Lykke.Service.Bitcoin.Sign/Controllers/SignController.cs#L25

2018-09-08 18:28 UTC, sefbkn commented on src/Lykke.Service.Decred.SignService/Models/SignTransactionRequest.cs
> +    public class SignTransactionRequest : IValidatableObject
https://github.com/LykkeCity/Lykke.Service.Bitcoin.Sign/blob/dev/src/Lykke.Service.Bitcoin.Sign/Models/Sign/SignRequest.cs

2018-09-08 18:30 UTC, sefbkn commented
@PaterSantyago Please re-review the code.  I've updated to source to address a few issues and need further clarification.

2018-09-10 08:03 UTC, PaterSantyago requested changes

2018-09-10 08:03 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/SignTransactionRequest.cs
> +    public class SignTransactionRequest : IValidatableObject
Please, use Lykke.Service.BlockchainApi.Contract.Transactions.SignTransactionRequest

2018-09-10 08:03 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Core/Domain/WalletCreationResponse.cs
> +    public class WalletCreationResponse
Usually, models are not domain objects. Moreover, please, use Lykke.Service.BlockchainApi.Contract.Wallets.WalletResponse

2018-09-10 08:03 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/ErrorResponse.cs
> +    public class ErrorResponse
As I note earlier, please, use either Lykke.Service.BlockchainApi.Contract. BlockchainErrorResponse, or Lykke.Common.Api.Contract.Responses.ErrorResponse

2018-09-10 08:03 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService/Models/IsAliveResponse.cs
> +    public class IsAliveResponse
This model is not necessary

2018-09-10 08:03 UTC, PaterSantyago commented on src/Lykke.Service.Decred.SignService.Services/SigningService.cs
> +    public interface ISigningService
Move interface to the Core project

2018-09-16 07:21 UTC, PaterSantyago approved these changes

2018-09-20 18:06 UTC, merged